# Generated by Django 3.2.10 on 2022-12-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='todo',
            field=models.ManyToManyField(related_name='tags', to='todo.Todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.user'),
        ),
    ]
