# Generated by Django 3.2.10 on 2022-12-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chats.chatroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chatroom',
            field=models.ManyToManyField(blank=True, null=True, related_name='chatroom_user', to='chats.Chatroom'),
        ),
    ]
